// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJtuyHzdjaN-7S6vOUcP8n0cYqMKxjcE',
    appId: '1:740523113965:web:e0c17db45a2314829ebbe4',
    messagingSenderId: '740523113965',
    projectId: 'yokubo-9ae1b',
    authDomain: 'yokubo-9ae1b.firebaseapp.com',
    storageBucket: 'yokubo-9ae1b.appspot.com',
    measurementId: 'G-19X2HGEE4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebsg56lvtLCjDAKvNLON_aFy1KyEajRY',
    appId: '1:740523113965:android:66401fb5fc34fdf59ebbe4',
    messagingSenderId: '740523113965',
    projectId: 'yokubo-9ae1b',
    storageBucket: 'yokubo-9ae1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiTnautyX6ae5_fkhEbGlTDkCnN5x5YTI',
    appId: '1:740523113965:ios:c0f1569b0f1b6deb9ebbe4',
    messagingSenderId: '740523113965',
    projectId: 'yokubo-9ae1b',
    storageBucket: 'yokubo-9ae1b.appspot.com',
    iosClientId: '740523113965-uk3o2kccpcff2qs9ora9fcr3mit0oul5.apps.googleusercontent.com',
    iosBundleId: 'com.simohimo.yokubo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiTnautyX6ae5_fkhEbGlTDkCnN5x5YTI',
    appId: '1:740523113965:ios:c0f1569b0f1b6deb9ebbe4',
    messagingSenderId: '740523113965',
    projectId: 'yokubo-9ae1b',
    storageBucket: 'yokubo-9ae1b.appspot.com',
    iosClientId: '740523113965-uk3o2kccpcff2qs9ora9fcr3mit0oul5.apps.googleusercontent.com',
    iosBundleId: 'com.simohimo.yokubo',
  );
}
